# MetaPM Cloud Build Configuration
# Triggered by pushes to main branch

steps:
  # Run tests - TEMPORARILY DISABLED: ODBC drivers not available in test container
  # - name: 'python:3.11-slim'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       pip install -r requirements.txt
  #       pip install pytest pytest-asyncio
  #       python -m pytest tests/ -v --tb=short
  #   id: 'test'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/metapm:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/metapm:latest'
      - '.'
    id: 'build'
    # waitFor: ['test']  # DISABLED while tests are disabled

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/metapm:$COMMIT_SHA'
    id: 'push'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/metapm:latest'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'metapm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/metapm:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'DB_SERVER=/cloudsql/${_CLOUD_SQL_INSTANCE},DB_NAME=MetaPM,DB_USER=sqlserver,ENVIRONMENT=production'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
    id: 'deploy'
    waitFor: ['push']

# Substitution variables (set in Cloud Build trigger)
substitutions:
  _CLOUD_SQL_INSTANCE: 'your-project:us-central1:your-instance'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Images to store
images:
  - 'gcr.io/$PROJECT_ID/metapm:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/metapm:latest'

timeout: '1200s'
