"""
MP47 REQ-085: Seed data for mcp_tool_metadata.

Categories: state_write, state_read, semantic_search, workflow, discovery, content_retrieval.
Servers: metapm, portfolio-rag, gmail, calendar, drive, builtin.
"""

TOOL_METADATA_SEED = [
    # ── MetaPM MCP (22) ────────────────────────────────────────────────────
    {
        "tool_name": "post_prompt",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CAI calls after 5Q readiness check to create a CC sprint prompt.",
        "forbidden_uses": "Do not call during an executing sprint — only at sprint kickoff.",
        "gotchas": "project_id is a UUID — look up via /api/roadmap/projects before calling.",
    },
    {
        "tool_name": "reject_prompt",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "PL or CAI rejects a prompt that fails readiness review.",
        "forbidden_uses": "CC must never call this on its own prompt.",
        "gotchas": "Requires a human-readable reason; archived prompts cannot be reopened.",
    },
    {
        "tool_name": "post_uat_spec",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CAI creates a UAT spec at prompt-creation time with structured test_cases.",
        "forbidden_uses": "Do not post with empty test_cases — server rejects (BA16).",
        "gotchas": "Upserts by PTH (AP04 Fix 4) — same PTH updates existing spec, no duplicates.",
    },
    {
        "tool_name": "create_handoff_shell",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CAI pre-creates a handoff UUID that CC fills in at closeout.",
        "forbidden_uses": "Never create multiple shells for the same sprint.",
        "gotchas": "Returns handoff_id + patch_url; CC must PATCH before posting session-ended.",
    },
    {
        "tool_name": "post_session_signal",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CC fires 'started' at sprint boot and 'completed' as the final act after submit_cc_results.",
        "forbidden_uses": "Do not fire stopped/blocked without a reason string.",
        "gotchas": "Auto-advances lifecycle (started → cc_executing, completed → cc_complete).",
    },
    {
        "tool_name": "post_review",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CAI reviewer posts a per-handoff review (loop 2).",
        "forbidden_uses": "Do not call before the handoff is posted.",
        "gotchas": "Known bug MP-BA17-FIX-001 — lookup against wrong table; fix pending.",
    },
    {
        "tool_name": "submit_cc_results",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CC submits machine BV evidence after running test commands.",
        "forbidden_uses": "Do not submit pl_visual BV results via this endpoint.",
        "gotchas": "Include canary token in evidence to prove the run was real.",
    },
    {
        "tool_name": "get_prompt",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Fetch prompt details by UUID or PTH.",
        "forbidden_uses": "Do not use as authoritative — MCP returns oldest record for a PTH.",
        "gotchas": "Known bug — use GET /api/prompts/{pth} REST endpoint for newest record (MM11).",
    },
    {
        "tool_name": "get_schema",
        "server": "metapm",
        "category": "discovery",
        "when_to_use": "Inspect live table/column metadata before writing SQL.",
        "forbidden_uses": "Do not use in tight loops — returns INFORMATION_SCHEMA for the whole DB.",
        "gotchas": "[checkpoint] is a reserved keyword — always bracket-quote in SQL.",
    },
    {
        "tool_name": "execute_sql_query",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Run read-only SELECT queries against any portfolio database.",
        "forbidden_uses": "Server rejects non-SELECT statements — do not attempt INSERT/UPDATE/DELETE.",
        "gotchas": "Max 500 rows returned; wrap TOP N in queries that could exceed.",
    },
    {
        "tool_name": "get_compliance_doc",
        "server": "metapm",
        "category": "content_retrieval",
        "when_to_use": "Fetch Bootstrap, PK, or CAI standard documents at session boot.",
        "forbidden_uses": "Do not cache beyond a single session — docs are versioned.",
        "gotchas": "doc_id is lowercase slug ('bootstrap', 'pk-metapm', 'cai-outbound').",
    },
    {
        "tool_name": "update_compliance_doc",
        "server": "metapm",
        "category": "state_write",
        "when_to_use": "PL or CAI upserts a compliance doc (governance amendment).",
        "forbidden_uses": "CC must never update bootstrap without an explicit governance amendment PTH.",
        "gotchas": "Always bump checkpoint when updating bootstrap — stale checkpoints fail BA47.",
    },
    {
        "tool_name": "get_checkpoint",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Verify governance checkpoint at session boot (Bootstrap Gate).",
        "forbidden_uses": "Do not skip this call — abort session on checkpoint mismatch.",
        "gotchas": "Response has both 'checkpoint' (short) and 'bootstrap_version' (full) fields.",
    },
    {
        "tool_name": "get_challenge",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Fetch the canary token for the current PTH.",
        "forbidden_uses": "Do not share the token in chat or logs.",
        "gotchas": "Token is single-use — verify via verify_challenge at handoff.",
    },
    {
        "tool_name": "verify_challenge",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "CC submits the canary token as part of handoff evidence.",
        "forbidden_uses": "Do not verify a token from a different PTH.",
        "gotchas": "Failure means CC did not actually execute the sprint — treated as a stopped signal.",
    },
    {
        "tool_name": "list_projects",
        "server": "metapm",
        "category": "discovery",
        "when_to_use": "Look up project UUIDs before calling post_prompt or post_requirement.",
        "forbidden_uses": "Do not hardcode project UUIDs — they may rotate.",
        "gotchas": "Also available unauthenticated at GET /api/roadmap/projects.",
    },
    {
        "tool_name": "list_requirements",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Browse the backlog for a project by status.",
        "forbidden_uses": "Do not filter client-side — pass project_code to narrow.",
        "gotchas": "Requirement code field is capped at 20 characters.",
    },
    {
        "tool_name": "post_requirement",
        "server": "metapm",
        "category": "state_write",
        "when_to_use": "Seed a new backlog item (req or bug) on a project.",
        "forbidden_uses": "Do not create duplicates — check list_requirements first.",
        "gotchas": "priority enum is P1/P2/P3; status defaults to req_created (lifecycle v2.11.0).",
    },
    {
        "tool_name": "patch_requirement_status",
        "server": "metapm",
        "category": "state_write",
        "when_to_use": "Advance a requirement through lifecycle states manually.",
        "forbidden_uses": "Do not bypass auto-advance — prefer session signals.",
        "gotchas": "Use PATCH /state (not PUT) — body {status, override_gate:true} bypasses closeout gate.",
    },
    {
        "tool_name": "get_requirement_history",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Inspect the lifecycle transition history for a requirement (MP37).",
        "forbidden_uses": "Do not use for dashboard counts — hits requirement_history row-by-row.",
        "gotchas": "Only returns rows where trg_cc_prompts_status_audit fired; manual inserts skip audit.",
    },
    {
        "tool_name": "get_uat_results",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Read PL-submitted UAT results by spec UUID.",
        "forbidden_uses": "Do not use to trigger re-opens — fetch via reopen endpoint instead.",
        "gotchas": "Returns current state of test_cases_json, not a historical snapshot.",
    },
    {
        "tool_name": "get_uat_results_by_pth",
        "server": "metapm",
        "category": "state_read",
        "when_to_use": "Shortcut lookup by PTH (no UUID needed).",
        "forbidden_uses": "Do not use when multiple specs share a PTH — returns newest only.",
        "gotchas": "No auth required; safe for public read.",
    },
    {
        "tool_name": "trigger_rag_sync",
        "server": "metapm",
        "category": "workflow",
        "when_to_use": "Kick Portfolio RAG to re-index after a schema or doc change.",
        "forbidden_uses": "Do not call in a loop — sync is heavy.",
        "gotchas": "Fire-and-forget; success returns 202 but indexing takes minutes.",
    },

    # ── Portfolio RAG (3) ──────────────────────────────────────────────────
    {
        "tool_name": "rag_query",
        "server": "portfolio-rag",
        "category": "semantic_search",
        "when_to_use": "General semantic lookup across active collections.",
        "forbidden_uses": "Do not treat results as authoritative — always verify in source code.",
        "gotchas": "Collection list changed in v3.0 — etymology-only after MP35.",
    },
    {
        "tool_name": "query_portfolio",
        "server": "portfolio-rag",
        "category": "semantic_search",
        "when_to_use": "Search portfolio documentation (requirements, compliance docs).",
        "forbidden_uses": "Do not use for code search — empty after v3.0 deletion.",
        "gotchas": "Fallback to /api/search/knowledge SQL search for portfolio-wide code/docs (PR-V3-ARCH-001).",
    },
    {
        "tool_name": "rag_get_document",
        "server": "portfolio-rag",
        "category": "content_retrieval",
        "when_to_use": "Fetch a full document by ID after a hit in rag_query.",
        "forbidden_uses": "Do not list-scan — use semantic query first.",
        "gotchas": "Document IDs are collection-scoped; passing wrong collection returns 404.",
    },

    # ── Gmail (6) ──────────────────────────────────────────────────────────
    {
        "tool_name": "create_draft",
        "server": "gmail",
        "category": "state_write",
        "when_to_use": "Compose a draft without sending (user reviews before send).",
        "forbidden_uses": "Do not auto-send — Gmail MCP only drafts.",
        "gotchas": "Threading by replyTo requires the original message ID.",
    },
    {
        "tool_name": "search_threads",
        "server": "gmail",
        "category": "state_read",
        "when_to_use": "Find threads by Gmail search query syntax (from:, subject:, etc.).",
        "forbidden_uses": "Do not use to bulk-export — hit rate limits quickly.",
        "gotchas": "Returns thread IDs only — call get_thread for bodies.",
    },
    {
        "tool_name": "get_thread",
        "server": "gmail",
        "category": "content_retrieval",
        "when_to_use": "Read full thread contents after search_threads.",
        "forbidden_uses": "Do not paginate in tight loops.",
        "gotchas": "Large threads may be truncated — check message count.",
    },
    {
        "tool_name": "label_message",
        "server": "gmail",
        "category": "state_write",
        "when_to_use": "Apply a label to a single message.",
        "forbidden_uses": "Do not use for thread-wide labeling — use label_thread.",
        "gotchas": "Label IDs not names — call list_labels first.",
    },
    {
        "tool_name": "label_thread",
        "server": "gmail",
        "category": "state_write",
        "when_to_use": "Apply a label to every message in a thread.",
        "forbidden_uses": "Do not apply system labels (INBOX, SENT, DRAFT) without intent.",
        "gotchas": "Removing INBOX archives the thread.",
    },
    {
        "tool_name": "list_labels",
        "server": "gmail",
        "category": "discovery",
        "when_to_use": "Resolve label names to IDs.",
        "forbidden_uses": "Do not call on every request — cache for the session.",
        "gotchas": "System labels have uppercase IDs (INBOX); user labels are Label_XXX.",
    },

    # ── Google Calendar (8) ────────────────────────────────────────────────
    {
        "tool_name": "list_calendars",
        "server": "calendar",
        "category": "discovery",
        "when_to_use": "Find calendar IDs before any event operation.",
        "forbidden_uses": "Do not assume 'primary' — user may have multiple calendars.",
        "gotchas": "primary calendar ID equals user email for most accounts.",
    },
    {
        "tool_name": "list_events",
        "server": "calendar",
        "category": "state_read",
        "when_to_use": "Scan a date range for existing events before scheduling.",
        "forbidden_uses": "Do not overlap list_events with suggest_time in a loop.",
        "gotchas": "Default pageSize is 250 — use timeMin/timeMax to narrow.",
    },
    {
        "tool_name": "get_event",
        "server": "calendar",
        "category": "content_retrieval",
        "when_to_use": "Fetch full event details by ID.",
        "forbidden_uses": "Do not call for list-like queries — use list_events.",
        "gotchas": "Recurring event instance IDs have suffix _YYYYMMDDTHHMMSSZ.",
    },
    {
        "tool_name": "create_event",
        "server": "calendar",
        "category": "state_write",
        "when_to_use": "Schedule a new event after confirming with user.",
        "forbidden_uses": "Never create events silently — always surface the detail.",
        "gotchas": "Attendee emails must be on user's domain or prior contacts.",
    },
    {
        "tool_name": "update_event",
        "server": "calendar",
        "category": "state_write",
        "when_to_use": "Modify an existing event (time, attendees, description).",
        "forbidden_uses": "Do not blanket-replace — pass only the fields that change.",
        "gotchas": "sendUpdates controls notification; default is 'all'.",
    },
    {
        "tool_name": "delete_event",
        "server": "calendar",
        "category": "state_write",
        "when_to_use": "Remove an event the user confirms cancellation of.",
        "forbidden_uses": "Do not delete without user confirmation — irreversible.",
        "gotchas": "Deleting a recurring series instance may only cancel that occurrence.",
    },
    {
        "tool_name": "suggest_time",
        "server": "calendar",
        "category": "workflow",
        "when_to_use": "Find free slots across multiple attendees.",
        "forbidden_uses": "Do not use for solo scheduling — overkill.",
        "gotchas": "Works against freeBusy — private event detail stays hidden.",
    },
    {
        "tool_name": "respond_to_event",
        "server": "calendar",
        "category": "state_write",
        "when_to_use": "Accept/decline/tentative an invitation on the user's behalf.",
        "forbidden_uses": "Do not auto-respond without user instruction.",
        "gotchas": "comment is shown to the organizer.",
    },

    # ── Google Drive (7) ───────────────────────────────────────────────────
    {
        "tool_name": "search_files",
        "server": "drive",
        "category": "discovery",
        "when_to_use": "Find files by name or MIME type.",
        "forbidden_uses": "Do not recurse entire Drive — scope with fullText or name.",
        "gotchas": "Drive search syntax differs from Gmail; supports contains/=.",
    },
    {
        "tool_name": "list_recent_files",
        "server": "drive",
        "category": "state_read",
        "when_to_use": "Show recently edited files (dashboards, homepage surfaces).",
        "forbidden_uses": "Do not paginate past 100 — add modifiedTime filter.",
        "gotchas": "Includes files shared with the user, not just owned.",
    },
    {
        "tool_name": "get_file_metadata",
        "server": "drive",
        "category": "state_read",
        "when_to_use": "Inspect a file's MIME type, size, owners, and permissions.",
        "forbidden_uses": "Do not use for full content — use read_file_content.",
        "gotchas": "exportLinks only populated for Google-native files (Docs, Sheets, Slides).",
    },
    {
        "tool_name": "read_file_content",
        "server": "drive",
        "category": "content_retrieval",
        "when_to_use": "Read text/spreadsheet contents into context.",
        "forbidden_uses": "Do not read binary files — use download_file_content.",
        "gotchas": "Google Docs returns markdown; Sheets returns CSV of the first tab.",
    },
    {
        "tool_name": "download_file_content",
        "server": "drive",
        "category": "content_retrieval",
        "when_to_use": "Fetch binary file content (PDF, image, zip).",
        "forbidden_uses": "Do not download Google-native files — export them via read_file_content.",
        "gotchas": "Large files (>10MB) may exceed response limits.",
    },
    {
        "tool_name": "create_file",
        "server": "drive",
        "category": "state_write",
        "when_to_use": "Write a new file to Drive (scratch notes, exports).",
        "forbidden_uses": "Do not overwrite user files without confirmation.",
        "gotchas": "parents[] must be folder IDs, not names.",
    },
    {
        "tool_name": "get_file_permissions",
        "server": "drive",
        "category": "state_read",
        "when_to_use": "Inspect who can see or edit a file before sharing.",
        "forbidden_uses": "Do not enumerate for files not owned by the user.",
        "gotchas": "domain-wide shares appear as a single permission row.",
    },
]
